### PR TITLE
fix: change listdatabase title type from string to []TextObject

### PR DESCRIPTION
**Pull request by mustafasegf**
## WHY
List database return []TextObject and not string. The notion documentation is wrong. This is the json i got from my curl.
```json
{
    "object": "list",
    "results": [
        {
            "object": "database",
            "id": "00000000-0000-0000-0000-000000000000",
            "created_time": "2021-05-26T11:07:57.029Z",
            "last_edited_time": "2021-05-26T11:08:00.000Z",
            "title": [
                {
                    "type": "text",
                    "text": {
                        "content": "test",
                        "link": null
                    },
                    "annotations": {
                        "bold": false,
                        "italic": false,
                        "strikethrough": false,
                        "underline": false,
                        "code": false,
                        "color": "default"
                    },
                    "plain_text": "test",
                    "href": null
                }
            ],
            "properties": {
                "Tags": {
                    "id": "ZVRw",
                    "type": "multi_select",
                    "multi_select": {
                        "options": []
                    }
                },
                "Name": {
                    "id": "title",
                    "type": "title",
                    "title": {}
                }
            }
        }
    ],
    "next_cursor": null,
    "has_more": false
}
```

### CODE REVIEW

**Comment by KeisukeYamashita** [comment]
Thanks for your PR.
I found that the ListDatabase API returns `title` property with array of Text objects not a string.
The official document is wrong https://developers.notion.com/reference/get-databases

**Comment by KeisukeYamashita** [comment]
@mustafasegf Can you also update the test case for me, please? Please run `go test ./...` in your local env first.

**Comment by mustafasegf** [comment]
sure i'll change the test case

**Comment by mustafasegf** [comment]
@KeisukeYamashita Did the change, you can check it

**Review by KeisukeYamashita — APPROVED** [review]
@mustafasegf LGTM!Thanks for catching this🙏

**Pull request merged**
